"use client";

import { FormEvent, useEffect, useState } from "react";
import { DashboardShell } from "@/components/DashboardShell";
import { createSupabaseBrowserClient } from "@/lib/auth";

type Method={id:string;name:string;account_name:string|null;account_number:string|null;active:boolean;sort_order:number};

export default function AdminSettingsPage(){
  const[contact,setContact]=useState({phone:"+252 63 4199277",whatsapp:"+252 63 4199277",email:"ridwaancabdi888@gmail.com"});
  const[commission,setCommission]=useState({default_percent:8,airport_fee:0,intercity_fee:0});
  const[methods,setMethods]=useState<Method[]>([]);const[message,setMessage]=useState("");
  async function load(){try{const supabase=createSupabaseBrowserClient();const[{data:settings},{data:paymentMethods}]=await Promise.all([supabase.from("site_settings").select("key,value"),supabase.from("payment_methods").select("id,name,account_name,account_number,active,sort_order").order("sort_order")]);for(const item of settings||[]){if(item.key==="contact")setContact(item.value);if(item.key==="commission")setCommission(item.value)}setMethods(paymentMethods||[])}catch(error){setMessage(error instanceof Error?error.message:"Settings lama soo qaadi karin.")}}
  useEffect(()=>{load()},[]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();try{const supabase=createSupabaseBrowserClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return;const rows=[{key:"contact",value:contact,updated_by:user.id,updated_at:new Date().toISOString()},{key:"commission",value:commission,updated_by:user.id,updated_at:new Date().toISOString()}];const{error}=await supabase.from("site_settings").upsert(rows);if(error)throw error;await supabase.from("audit_logs").insert({actor_id:user.id,action:"settings.updated",entity_type:"site_settings",metadata:{contact,commission}});setMessage("Settings-ka waa la kaydiyey.")}catch(error){setMessage(error instanceof Error?error.message:"Settings lama kaydin.")}}
  async function updateMethod(id:string,changes:Record<string,unknown>){const supabase=createSupabaseBrowserClient();const{error}=await supabase.from("payment_methods").update(changes).eq("id",id);if(error)return setMessage(error.message);load()}
  return <DashboardShell title="Platform Settings"><form className="settings-section" onSubmit={save}><section className="card"><h2>Contact information</h2><div className="form-grid"><div className="field"><label>Phone</label><input value={contact.phone} onChange={e=>setContact({...contact,phone:e.target.value})}/></div><div className="field"><label>WhatsApp</label><input value={contact.whatsapp} onChange={e=>setContact({...contact,whatsapp:e.target.value})}/></div><div className="field"><label>Email</label><input type="email" value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/></div></div></section><section className="card"><h2>Commission & fees</h2><div className="form-grid"><div className="field"><label>Default commission %</label><input type="number" value={commission.default_percent} onChange={e=>setCommission({...commission,default_percent:Number(e.target.value)})}/></div><div className="field"><label>Airport fee</label><input type="number" value={commission.airport_fee} onChange={e=>setCommission({...commission,airport_fee:Number(e.target.value)})}/></div><div className="field"><label>Intercity fee</label><input type="number" value={commission.intercity_fee} onChange={e=>setCommission({...commission,intercity_fee:Number(e.target.value)})}/></div></div></section><button className="btn btn-primary">Kaydi settings-ka</button>{message&&<p className="form-message">{message}</p>}</form><section className="section"><div className="card"><h2>Payment methods</h2><div className="table-scroll"><table className="table"><thead><tr><th>Method</th><th>Account name</th><th>Account number</th><th>Active</th></tr></thead><tbody>{methods.map(method=><tr key={method.id}><td><strong>{method.name}</strong></td><td><input defaultValue={method.account_name||""} onBlur={e=>updateMethod(method.id,{account_name:e.target.value})}/></td><td><input defaultValue={method.account_number||""} onBlur={e=>updateMethod(method.id,{account_number:e.target.value})}/></td><td><input type="checkbox" checked={method.active} onChange={e=>updateMethod(method.id,{active:e.target.checked})}/></td></tr>)}</tbody></table></div></div></section></DashboardShell>
}
