"use client";

import { FormEvent, useMemo, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/auth";

export default function BookingPage(){
  const [days,setDays]=useState(3); const [driver,setDriver]=useState(true); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
  const subtotal=useMemo(()=>days*95+(driver?days*15:0),[days,driver]); const fee=Math.round(subtotal*.08); const total=subtotal+fee;
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setMessage("");try{const supabase=createSupabaseBrowserClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Fadlan marka hore soo gal.");const form=new FormData(e.currentTarget);const {error}=await supabase.from("bookings").insert({customer_id:user.id,vehicle_id:String(form.get("vehicleId")),pickup_at:String(form.get("pickupAt")),return_at:String(form.get("returnAt")),rental_type:String(form.get("rentalType")),driver_required:driver,subtotal,commission_amount:fee,total,status:"awaiting_payment"});if(error)throw error;setMessage("Booking-ka waa la gudbiyey. Hadda dooro lacag-bixinta.");}catch(error){setMessage(error instanceof Error?error.message:"Booking-ku wuu fashilmay.");}finally{setLoading(false)}}
  return <main className="section"><div className="container"><span className="eyebrow">Checkout</span><h1 className="details-title">Dhammaystir booking-ka</h1><form className="checkout-grid" onSubmit={submit}><section className="card auth-form"><input type="hidden" name="vehicleId" value="00000000-0000-0000-0000-000000000001"/><div className="field"><label>Pickup date & time</label><input name="pickupAt" type="datetime-local" required/></div><div className="field"><label>Return date & time</label><input name="returnAt" type="datetime-local" required/></div><div className="field"><label>Muddada maalmaha</label><input type="number" min="1" value={days} onChange={e=>setDays(Number(e.target.value))}/></div><div className="field"><label>Habka kirada</label><select name="rentalType"><option value="daily">Maalinle</option><option value="hourly">Saacadle</option><option value="intercity">Safar magaalo kale</option><option value="airport">Airport pickup</option></select></div><label className="checkbox"><input type="checkbox" checked={driver} onChange={e=>setDriver(e.target.checked)}/> Darawal ku dar ($15 maalintii)</label><div className="field"><label>Habka lacag-bixinta</label><select name="paymentMethod"><option>ZAAD</option><option>E-Dahab</option><option>EVC Plus</option><option>Sahal</option><option>Cash / Pay on pickup</option></select></div><button className="btn btn-primary" disabled={loading}>{loading?"Waa la gudbinayaa...":"Xaqiiji booking-ka"}</button>{message&&<p className="form-message">{message}</p>}</section><aside className="booking-card"><h2>Toyota One Ten</h2><p className="muted">Hargeysa · Verified company</p><div className="summary-line"><span>Kirada</span><strong>${days*95}</strong></div><div className="summary-line"><span>Darawal</span><strong>${driver?days*15:0}</strong></div><div className="summary-line"><span>Service fee</span><strong>${fee}</strong></div><div className="summary-line total"><span>Total</span><strong>${total}</strong></div><p className="muted">Payment-ka manual verification ayuu ahaanayaa ilaa mobile-money API la xiro.</p></aside></form></div></main>
}
