"use client";

import { FormEvent, useEffect, useState } from "react";
import { DashboardShell } from "@/components/DashboardShell";
import { createSupabaseBrowserClient } from "@/lib/auth";

type Company={id:string;name:string;phone:string|null;whatsapp:string|null;email:string|null;status:string};

export default function CompanyOnboardingPage(){
  const[company,setCompany]=useState<Company|null>(null);const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);
  useEffect(()=>{(async()=>{try{const supabase=createSupabaseBrowserClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data}=await supabase.from("companies").select("id,name,phone,whatsapp,email,status").eq("owner_id",user.id).limit(1).maybeSingle();setCompany(data)}catch(error){setMessage(error instanceof Error?error.message:"Company profile lama soo qaadi karin.")}})()},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage("");try{const supabase=createSupabaseBrowserClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Fadlan soo gal.");const form=new FormData(event.currentTarget);const name=String(form.get("name"));const slug=`${name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")}-${user.id.slice(0,6)}`;const payload={owner_id:user.id,name,slug,phone:String(form.get("phone")),whatsapp:String(form.get("whatsapp")),email:String(form.get("email")),status:"pending"};const request=company?supabase.from("companies").update(payload).eq("id",company.id).select("id,name,phone,whatsapp,email,status").single():supabase.from("companies").insert(payload).select("id,name,phone,whatsapp,email,status").single();const{data,error}=await request;if(error)throw error;setCompany(data);setMessage("Company profile-ka waa la gudbiyey, wuxuuna sugayaa ansixinta Super Admin-ka.")}catch(error){setMessage(error instanceof Error?error.message:"Company profile lama kaydin.")}finally{setLoading(false)}}
  return <DashboardShell title="Company Profile"><div className="management-grid"><form className="card auth-form" onSubmit={submit}><span className={`badge status-${company?.status||"pending"}`}>{company?.status||"New company"}</span><h2>{company?"Wax ka beddel company-ga":"Diiwaangeli company-ga"}</h2><div className="field"><label>Company name</label><input name="name" required defaultValue={company?.name||""}/></div><div className="field"><label>Phone</label><input name="phone" required defaultValue={company?.phone||""}/></div><div className="field"><label>WhatsApp</label><input name="whatsapp" required defaultValue={company?.whatsapp||""}/></div><div className="field"><label>Email</label><input name="email" type="email" required defaultValue={company?.email||""}/></div><button className="btn btn-primary" disabled={loading}>{loading?"Waa la kaydinayaa...":company?"Cusboonaysii company-ga":"Gudbi company-ga"}</button>{message&&<p className="form-message">{message}</p>}</form><aside className="card"><h2>Waxa xiga</h2><div className="list-stack"><div className="document-row"><span>1. Company profile</span><span className="badge">{company?"Done":"Current"}</span></div><div className="document-row"><span>2. Documents verification</span><span className="badge">Next</span></div><div className="document-row"><span>3. Admin approval</span><span className="badge">Pending</span></div><div className="document-row"><span>4. Add vehicles & employees</span><span className="badge">After approval</span></div></div><p className="muted">Company registration, business licence iyo owner ID waxaa lagu dari doonaa verification documents-ka.</p></aside></div></DashboardShell>
}
