"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { DashboardShell } from "@/components/DashboardShell";
import { createSupabaseBrowserClient } from "@/lib/auth";

type Vehicle={id:string;name:string;booking_count:number;rating:number;status:string};
type Booking={id:string;status:string;total:number;commission_amount:number;created_at:string};
type Company={id:string;status:string};

export default function AdminDashboard(){
  const[vehicles,setVehicles]=useState<Vehicle[]>([]);const[bookings,setBookings]=useState<Booking[]>([]);const[companies,setCompanies]=useState<Company[]>([]);const[users,setUsers]=useState(0);const[pendingPayments,setPendingPayments]=useState(0);const[message,setMessage]=useState("");
  useEffect(()=>{(async()=>{try{const supabase=createSupabaseBrowserClient();const[{data:v,error:ve},{data:b,error:be},{data:c,error:ce},{count:u,error:ue},{count:p,error:pe}]=await Promise.all([supabase.from("vehicles").select("id,name,booking_count,rating,status").order("booking_count",{ascending:false}).limit(20),supabase.from("bookings").select("id,status,total,commission_amount,created_at").order("created_at",{ascending:false}).limit(1000),supabase.from("companies").select("id,status"),supabase.from("profiles").select("id",{count:"exact",head:true}),supabase.from("payments").select("id",{count:"exact",head:true}).eq("status","pending")]);if(ve||be||ce||ue||pe)throw ve||be||ce||ue||pe;setVehicles(v||[]);setBookings(b||[]);setCompanies(c||[]);setUsers(u||0);setPendingPayments(p||0)}catch(error){setMessage(error instanceof Error?error.message:"Admin dashboard lama soo qaadi karin.")}})()},[]);
  const metrics=useMemo(()=>({activeVehicles:vehicles.filter(x=>x.status==="available").length,totalRevenue:bookings.filter(x=>x.status==="completed").reduce((a,b)=>a+Number(b.total||0),0),commission:bookings.filter(x=>x.status==="completed").reduce((a,b)=>a+Number(b.commission_amount||0),0),activeBookings:bookings.filter(x=>["confirmed","in_progress"].includes(x.status)).length}),[vehicles,bookings]);
  const monthly=[0,1,2,3,4,5,6].map(index=>bookings.filter(item=>{const date=new Date(item.created_at);const now=new Date();const target=new Date(now.getFullYear(),now.getMonth()-6+index,1);return date.getFullYear()===target.getFullYear()&&date.getMonth()===target.getMonth()}).length);
  const max=Math.max(...monthly,1);
  return <DashboardShell title="Super Admin"><section className="kpis"><div className="kpi"><span className="muted">Total bookings</span><strong>{bookings.length}</strong><span>{metrics.activeBookings} active</span></div><div className="kpi"><span className="muted">Active vehicles</span><strong>{metrics.activeVehicles}</strong><span>{vehicles.length} loaded</span></div><div className="kpi"><span className="muted">Platform revenue</span><strong>${metrics.commission.toFixed(2)}</strong><span>${metrics.totalRevenue.toFixed(2)} gross</span></div><div className="kpi"><span className="muted">Verified companies</span><strong>{companies.filter(x=>x.status==="approved").length}</strong><span>{users} users</span></div></section>{message&&<p className="form-message">{message}</p>}<section className="section"><div className="admin-grid"><div className="card"><div className="row"><div><h2>Booking growth</h2><p className="muted">7dii bilood ee ugu dambeeyey</p></div><Link className="text-link" href="/admin/bookings">Faahfaahin</Link></div><div className="chart-placeholder">{monthly.map((value,index)=><div key={index} className="chart-bar" style={{height:`${Math.max(8,(value/max)*100)}%`}} title={`${value} bookings`}/>)}</div></div><div className="card"><h2>Waxyaabaha u baahan dareenka</h2><div className="list-stack"><Link className="document-row" href="/admin/approvals"><span>✅ Pending approvals</span><span className="badge">{companies.filter(x=>x.status==="pending").length+vehicles.filter(x=>x.status==="pending_approval").length}</span></Link><Link className="document-row" href="/admin/payments"><span>💳 Payment verification</span><span className="badge">{pendingPayments}</span></Link><Link className="document-row" href="/admin/users"><span>👥 Total users</span><span className="badge">{users}</span></Link></div></div></div></section><section className="section"><div className="card"><div className="section-head"><div><h2>Gaadiidka loogu kiraysiga badan yahay</h2><p className="muted">Performance-ka guud ee marketplace-ka</p></div><Link className="text-link" href="/admin/vehicles">Dhammaan eeg</Link></div><div className="table-scroll"><table className="table"><thead><tr><th>Gaadhi</th><th>Bookings</th><th>Rating</th><th>Status</th></tr></thead><tbody>{vehicles.slice(0,10).map(vehicle=><tr key={vehicle.id}><td><strong>{vehicle.name}</strong></td><td>{vehicle.booking_count||0}</td><td>★ {Number(vehicle.rating||0).toFixed(1)}</td><td><span className={`badge status-${vehicle.status}`}>{vehicle.status.replaceAll("_"," ")}</span></td></tr>)}</tbody></table></div></div></section></DashboardShell>
}
