"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { DashboardShell } from "@/components/DashboardShell";
import { createSupabaseBrowserClient } from "@/lib/auth";

type Booking={id:string;status:string;pickup_at:string;return_at:string;total:number;vehicles:{name:string}|null};

export default function CustomerDashboard(){
  const[items,setItems]=useState<Booking[]>([]);const[notifications,setNotifications]=useState(0);const[message,setMessage]=useState("");
  useEffect(()=>{(async()=>{try{const supabase=createSupabaseBrowserClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return;const[{data:bookings,error},{count}]=await Promise.all([supabase.from("bookings").select("id,status,pickup_at,return_at,total,vehicles(name)").eq("customer_id",user.id).order("created_at",{ascending:false}),supabase.from("notifications").select("id",{count:"exact",head:true}).eq("user_id",user.id).is("read_at",null)]);if(error)throw error;setItems((bookings||[]) as unknown as Booking[]);setNotifications(count||0)}catch(error){setMessage(error instanceof Error?error.message:"Dashboard-ka lama soo qaadi karin.")}})()},[]);
  const stats=useMemo(()=>({upcoming:items.filter(x=>["pending","awaiting_payment","confirmed"].includes(x.status)).length,completed:items.filter(x=>x.status==="completed").length,active:items.filter(x=>x.status==="in_progress").length,spent:items.filter(x=>x.status==="completed").reduce((a,b)=>a+Number(b.total||0),0)}),[items]);
  const next=items.find(x=>["pending","awaiting_payment","confirmed","in_progress"].includes(x.status));
  return <DashboardShell title="Safarradayda"><section className="kpis"><div className="kpi"><span className="muted">Upcoming</span><strong>{stats.upcoming}</strong></div><div className="kpi"><span className="muted">Active</span><strong>{stats.active}</strong></div><div className="kpi"><span className="muted">Completed</span><strong>{stats.completed}</strong></div><div className="kpi"><span className="muted">Total spent</span><strong>${stats.spent.toFixed(2)}</strong></div></section>{message&&<p className="form-message">{message}</p>}<section className="section"><div className="admin-grid"><div className="card"><div className="row"><h2>Booking-ka xiga</h2><Link className="text-link" href="/customer/bookings">Dhammaan eeg</Link></div>{next?<><span className={`badge status-${next.status}`}>{next.status.replaceAll("_"," ")}</span><h2>{next.vehicles?.name||"Gaadhi"}</h2><p className="muted">{new Date(next.pickup_at).toLocaleString()} → {new Date(next.return_at).toLocaleString()}</p><strong>${next.total}</strong></>:<div className="empty-state"><p>Booking soo socda ma jiro.</p><Link className="btn btn-primary" href="/vehicles">Raadi gaadhi</Link></div>}</div><div className="card"><h2>Waxqabad degdeg ah</h2><div className="list-stack"><Link className="document-row" href="/vehicles"><span>🚙 Raadi gaadhi cusub</span><span>→</span></Link><Link className="document-row" href="/customer/profile"><span>🪪 Xaqiiji documents-ka</span><span>→</span></Link><Link className="document-row" href="/customer/notifications"><span>🔔 Notifications</span><span className="badge">{notifications}</span></Link></div></div></div></section></DashboardShell>
}
