"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { createSupabaseBrowserClient } from "@/lib/auth";

type Ticket={id:string;subject:string;priority:string;status:string;created_at:string};

export default function SupportPage(){
  const[tickets,setTickets]=useState<Ticket[]>([]);const[message,setMessage]=useState("");const[loading,setLoading]=useState(false);
  async function load(){try{const supabase=createSupabaseBrowserClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data,error}=await supabase.from("support_tickets").select("id,subject,priority,status,created_at").eq("user_id",user.id).order("created_at",{ascending:false});if(error)throw error;setTickets(data||[])}catch(error){setMessage(error instanceof Error?error.message:"Tickets lama soo qaadi karin.")}}
  useEffect(()=>{load()},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setMessage("");try{const supabase=createSupabaseBrowserClient();const{data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/signin?next=/support";return}const form=new FormData(event.currentTarget);const{error}=await supabase.from("support_tickets").insert({user_id:user.id,subject:String(form.get("subject")),message:String(form.get("message")),priority:String(form.get("priority"))});if(error)throw error;setMessage("Support ticket-ka waa la gudbiyey.");event.currentTarget.reset();load()}catch(error){setMessage(error instanceof Error?error.message:"Ticket-ka lama gudbin.")}finally{setLoading(false)}}
  return <main className="section"><div className="container"><Link className="logo" href="/"><span className="logo-mark">K</span>Kireeye</Link><div className="section-head"><div><span className="eyebrow">Customer support</span><h1 className="details-title">Sideen kuu caawin karnaa?</h1><p className="lead">Booking, payment, company ama gaadhi la xiriira cabasho iyo su’aal halkan noogu soo dir.</p></div><a className="btn btn-secondary" href="https://wa.me/252634199277">WhatsApp</a></div><div className="management-grid"><form className="card auth-form" onSubmit={submit}><h2>Samee support ticket</h2><div className="field"><label>Subject</label><input name="subject" required/></div><div className="field"><label>Priority</label><select name="priority"><option>normal</option><option>low</option><option>high</option><option>urgent</option></select></div><div className="field"><label>Faahfaahinta</label><textarea name="message" rows={7} required/></div><button className="btn btn-primary" disabled={loading}>{loading?"Waa la dirayaa...":"Gudbi ticket"}</button>{message&&<p className="form-message">{message}</p>}</form><section className="card"><h2>Tickets-kaaga</h2><div className="list-stack">{tickets.map(ticket=><div className="document-row" key={ticket.id}><div><strong>{ticket.subject}</strong><p className="muted">{new Date(ticket.created_at).toLocaleString()} · {ticket.priority}</p></div><span className={`badge status-${ticket.status}`}>{ticket.status.replaceAll("_"," ")}</span></div>)}{!tickets.length&&<p className="empty-state">Ticket wali ma lihid.</p>}</div></section></div></div></main>
}
