"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { DashboardShell } from "@/components/DashboardShell";
import { createSupabaseBrowserClient } from "@/lib/auth";

type Vehicle={id:string;name:string;status:string;booking_count:number;rating:number;price_day:number|null};
type Booking={id:string;status:string;pickup_at:string;return_at:string;total:number;vehicles:{name:string}|null};
type Payment={amount:number;status:string;bookings:{commission_amount:number}|null};

export default function CompanyDashboard(){
  const[vehicles,setVehicles]=useState<Vehicle[]>([]);const[bookings,setBookings]=useState<Booking[]>([]);const[payments,setPayments]=useState<Payment[]>([]);const[message,setMessage]=useState("");
  useEffect(()=>{(async()=>{try{const supabase=createSupabaseBrowserClient();const[{data:v,error:ve},{data:b,error:be},{data:p,error:pe}]=await Promise.all([supabase.from("vehicles").select("id,name,status,booking_count,rating,price_day").order("booking_count",{ascending:false}),supabase.from("bookings").select("id,status,pickup_at,return_at,total,vehicles(name)").order("created_at",{ascending:false}).limit(100),supabase.from("payments").select("amount,status,bookings(commission_amount)").eq("status","approved")]);if(ve||be||pe)throw ve||be||pe;setVehicles(v||[]);setBookings((b||[]) as unknown as Booking[]);setPayments((p||[]) as unknown as Payment[])}catch(error){setMessage(error instanceof Error?error.message:"Dashboard-ka lama soo qaadi karin.")}})()},[]);
  const finance=useMemo(()=>payments.reduce((a,p)=>({gross:a.gross+Number(p.amount||0),commission:a.commission+Number(p.bookings?.commission_amount||0)}),{gross:0,commission:0}),[payments]);
  const pending=bookings.filter(x=>["pending","awaiting_payment"].includes(x.status));const active=bookings.filter(x=>["confirmed","in_progress"].includes(x.status));const top=vehicles.slice(0,5);
  return <DashboardShell title="Company Dashboard"><section className="kpis"><div className="kpi"><span className="muted">Gaadiid</span><strong>{vehicles.length}</strong></div><div className="kpi"><span className="muted">Rented now</span><strong>{bookings.filter(x=>x.status==="in_progress").length}</strong></div><div className="kpi"><span className="muted">Pending bookings</span><strong>{pending.length}</strong></div><div className="kpi"><span className="muted">Net earnings</span><strong>${(finance.gross-finance.commission).toFixed(2)}</strong></div></section>{message&&<p className="form-message">{message}</p>}<section className="section"><div className="admin-grid"><div className="card"><div className="row"><div><h2>Gaadiidka ugu shaqada badan</h2><p className="muted">Bookings iyo rating</p></div><Link className="text-link" href="/company/vehicles">Dhammaan eeg</Link></div><div className="list-stack">{top.map((vehicle,index)=><div className="document-row" key={vehicle.id}><div><strong>{index+1}. {vehicle.name}</strong><p className="muted">{vehicle.booking_count||0} bookings · ★ {Number(vehicle.rating||0).toFixed(1)}</p></div><span className={`badge status-${vehicle.status}`}>{vehicle.status.replaceAll("_"," ")}</span></div>)}{!top.length&&<p className="empty-state">Gaadhi wali lama darin.</p>}</div></div><div className="card"><div className="row"><h2>Hawlaha maanta</h2><Link className="text-link" href="/company/bookings">Bookings</Link></div><div className="status-grid"><div className="kpi"><span className="muted">Pending</span><strong>{pending.length}</strong></div><div className="kpi"><span className="muted">Active</span><strong>{active.length}</strong></div><div className="kpi"><span className="muted">Completed</span><strong>{bookings.filter(x=>x.status==="completed").length}</strong></div></div><div className="chart-placeholder">{[35,58,45,82,66,92,74].map((height,index)=><div key={index} className="chart-bar" style={{height:`${height}%`}}/>)}</div></div></div></section></DashboardShell>
}
